Add many tests and fix bugs to meet 90% coverage
johnklee/fpu pull request #49
Opened 2023-10-01 11:48 UTC by wkCircle

The PR is mainly related to #20 , but also fix some bugs by the way. 

The PR
- fix the bug of `CollecitonUtils.prepend` (add the list(), same as the append method)
- add its test in test_crud
- add `__str__` and `pass` to white list of coverage in `pyproject.toml`.
- add the test for `setHead`
- ...

The final test results (in python3.8): 
```zsh
$ make test 
coverage run -m pytest tests
====================================================================================== test session starts =======================================================================================
platform win32 -- Python 3.8.1, pytest-7.4.0, pluggy-1.2.0
configfile: pyproject.toml
collected 50 items

tests\unit\test_flist.py .........................                                                                                                                                          [ 50%]
tests\unit\test_fp.py .........................                                                                                                                                             [100%]

======================================================================================= 50 passed in 0.11s ======================================================================================= 
coverage report
Name              Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------
fpu\__init__.py       2      2      0      0     0%   1-2
fpu\errors.py         5      0      0      0   100%
fpu\flist.py        178      6     46      1    97%   6-8, 297, 370, 386
fpu\fp.py           258     28     44      4    88%   7-8, 184, 197, 217, 237, 243-246, 249, 260, 263-267, 284-286, 289, 324, 350, 353, 356, 359, 388, 400, 416
fpu\utils.py         13      0      6      0   100%
-------------------------------------------------------------
TOTAL               456     36     96      5    92%
```

2023-10-01 11:55 UTC, wkCircle commented on tests/unit/test_fp.py
> +    def test_foldLeft(self):
I rename it to distinguish it from newly added foldRight test cases

2023-10-01 11:56 UTC, wkCircle commented on tests/unit/test_fp.py
> +        self.assertEqual(weight, 1.9 + 0.26, 'Expect 1.9 (Real={})'.format(price))
make initial value more diverse to truly test both foldLeft and foldRight

2023-10-01 11:57 UTC, wkCircle commented on tests/unit/test_fp.py
> +        pass
not used in the class

2023-10-01 11:58 UTC, wkCircle commented on tests/unit/test_fp.py
> +        pass
remove self.df and define df in local since it is used only once.

2023-10-01 13:45 UTC, johnklee requested changes
Some comments may deserve your attention. Thanks for adding more unit test cases to increase the coverage and improvement of the code quality.

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_flist.py
> +    self.assertIsInstance(result, Nil)
Brilliant idea to add test case to cover corner case.  Two feedback for your reference. 
1. This is a good usage case in using [parameterized testing feature](https://docs.pytest.org/en/7.1.x/example/parametrize.html). 
2. Please keep the unit test case content to follow [AAA structure](https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80)

Below is sample code for reference:
```python
@pytest.mark.parametrize(
    "indicator,short_stop_func,expected",
    [
        pytest.param(
            0, lambda v: v > 3, 6, id="FAST",
        ),
        pytest.param(
            0, lambda v: v > -1, flist.nil, id="corner_case",
        ),
    ])
def test_api_fold_left_with_short_stop(
    indicator, short_stop_func, expected):
  # Arrange
  alist = fl(1, 2, 3, 4, 5)

  # Action
  result = alist.foldLeft(
      0, lambda a, b: a + b,
      short_stop_func=short_stop_func)

  # Assert
  # The folding operation will stop at element 4.
  # So we have folding result as 0 + 1 + 2 + 3 = 6
  assert result == expected
```

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_flist.py
> +  def test_api_foldReft(self):
According to the comment, maybe the name of unit test case should be `test_api_foldRight`?

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_flist.py
> +    self.assertEqual(120.0, alist.foldLeft(1.0, lambda a, e: a * e))
You might want to place this line in unit test case `test_api_foldLeft`

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_flist.py
> +    self.assertEqual(result, 15)
This is actually two unit test cases. You could leverage "[Parametrizing test](https://docs.pytest.org/en/7.1.x/example/parametrize.html)" feature to use same unit test case with different testing data to cover them together (or more).

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_flist.py
> +    def firstevens(n: int):
Nit: Maybe `even_number_generator(until: int)`

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_flist.py
>      self.assertEqual('[(1, 2), (1, 3), (2, 3), NIL]', str(fpu_comp_list))
Refer to [`Parametrizing tests`](https://docs.pytest.org/en/7.1.x/example/parametrize.html). Thanks for adding more unit test case to increase coverage. Good job.

2023-10-01 13:45 UTC, johnklee commented on fpu/fp.py
>      return nlist
We want to keep container as immutable to meet FP requirement. So possibly, we could do this way:
```python
nlist = CollectionUtils.copy(alist)   # tuple instance
return (e, ) + nlist
```

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_fp.py
> +        order = CollectionUtils.l(OrderLine(toothPaste, 2),
Nit: `orders`

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_fp.py
> +        self.assertEqual(price, 13.5 + 1.15, 'Expect 13.5 (Real={})'.format(weight))
Expect `14.65` (13.5 + 1.15)?

2023-10-01 13:45 UTC, johnklee commented on tests/unit/test_fp.py
> +        self.assertEqual(weight, 1.9 + 0.26, 'Expect 1.9 (Real={})'.format(price))
Expect `2.16`? (1.9 + 0.26)

2023-10-10 00:50 UTC, johnklee approved these changes
LGTM

2023-10-10 00:53 UTC, johnklee commented on tests/unit/test_flist.py
> +    # TODO: fpu/57 - pytest parameterize not supported in unittest class
Nit: If it makes sense to you, let's use Google style to make todo marker. e.g.:
```
# TODO(#57): pytest parameterize not supported in unittest class
```
FYI

2023-10-10 07:46 UTC, merged